### ISSUE TITLE
Missing variables at global level

### ISSUE THREAD

**Issue by leomillon** [pcimcioch/gitlab-ci-kotlin-dsl#6]
Hi!

First of all, thanks a lot for this DSL that will be very useful to create dynamic child-pipeline!

Your DSL seems quite complete but it seems that there is no way to define variables at a global level of the pipeline like the `GLOBAL_VAR` in this example (cf. https://docs.gitlab.com/ee/ci/variables/index.html#define-a-cicd-variable-in-the-gitlab-ciyml-file):
```yaml
variables:
  GLOBAL_VAR: "A global variable"

job1:
  variables:
    JOB_VAR: "A job variable"
  script:
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"

job2:
  script:
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"
```

Is there a way to define global variables with something that I missed?

Thanks in advance for your help,
Regards,
Léo

**Comment by pcimcioch** [comment]
Hi!
Yeah, this project was not updated for some time, so it may miss few features. I can see it is in fact missing possibility to set env variables on workflow level.

I can try adding this someday next week :)

You can also create PR with this change if you feel like it and I'll take a look at it

**Comment by pcimcioch** [comment]
Hi, `variables` on global level has been added in version `1.5.1`

**Comment by leomillon** [comment]
Hi!

Thanks for your additions! I just looked at it and while it's now available at the global level, it's only as a "`string: string` format.

On the global level, there are more options available to defined variables (especially for the UI form display), for example:

```yaml
variables:
  DEPLOY_ENVIRONMENT:
    value: "staging"
    options:
      - "production"
      - "staging"
      - "canary"
    description: "The deployment target. Set to 'staging' by default."
```

see:
- [Configure a list of selectable prefilled variable values](https://docs.gitlab.com/ee/ci/pipelines/index.html#configure-a-list-of-selectable-prefilled-variable-values)
- [variables:options](https://docs.gitlab.com/ee/ci/yaml/index.html#variablesoptions)
