### ISSUE TITLE
Multiple Cache

### ISSUE THREAD

**Issue by MrAolen** [pcimcioch/gitlab-ci-kotlin-dsl#7]
Hi !

Thanks for this beautiful DSL to create Gitlab CI pipeline.

I would to create multiple cache on a job. You can have an example right here in official documentation : https://docs.gitlab.com/ee/ci/caching/#use-multiple-caches :

```yml
test-job:
  stage: build
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
  script:
    - bundle config set --local path 'vendor/ruby'
    - bundle install
    - yarn install --cache-folder .yarn-cache
    - echo Run tests...
```
Is there a way to define mutiple caches with something that I missed?

Best regards !
